package cn.sz.kg.pojo;

import java.util.ArrayList;
import java.util.List;



// Generated 2017-3-20 10:45:45 by Hibernate Tools 3.4.0.CR1



/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {
	
	private Integer deptno;
	private String dname;
	private String loc;
	private List<Emp> emps = new ArrayList<Emp>(0);

	public Dept() {
	}

	public Dept(String dname) {
		this.dname = dname;
	}

	public Dept(String dname, String loc,List<Emp> emps) {
		this.dname = dname;
		this.loc = loc;
		this.emps = emps;
	}

	public Integer getDeptno() {
		return this.deptno;
	}

	public void setDeptno(Integer deptno) {
		this.deptno = deptno;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public List<Emp> getEmps() {
		return emps;
	}

	public void setEmps(List<Emp> emps) {
		this.emps = emps;
	}

	

}
