package cn.sz.kg.pojo;

// Generated 2017-3-21 17:40:03 by Hibernate Tools 3.4.0.CR1



/**
 * Users generated by hbm2java
 */

public class Users implements java.io.Serializable {

	private Integer id;
	private String username;
	private String pwd;
	private String rname;

	public Users() {
	}

	public Users(String username, String pwd, String rname) {
		this.username = username;
		this.pwd = pwd;
		this.rname = rname;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	
	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

}
